# ProGuard rules for Java N-IDE Modern
-keep class com.duy.** { *; }
-dontwarn com.duy.**
-keep class androidx.** { *; }
-dontwarn androidx.**
-keep class dagger.** { *; }
-dontwarn dagger.**
-keep class javax.** { *; }
-dontwarn javax.**
-keep class kotlin.** { *; }
-dontwarn kotlin.**
-keep class org.** { *; }
-dontwarn org.**
