name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run Tests
      run: ./gradlew test
      
    - name: Generate Test Report
      if: always()
      run: ./gradlew jacocoTestReport
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/reports/tests/
        
    - name: Upload Coverage Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-results
        path: app/build/reports/coverage/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-bundle
        
    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}
        packageName: com.duy.ide
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: beta